name: robotdreams-trading-fw
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pyyaml>=6.0
  - requests>=2.31.0
  - jupyterlab>=4.0.0
  - pytest>=7.4.0
  - pytest-cov>=4.0.0
  - pip
  - pip:
    - yfinance>=0.2.18
    - backtesting>=0.3.3
    - bokeh>=2.4.0,<3.0.0
    - ccxt>=4.2.0
    - python-dotenv>=1.0.0
    - schedule>=1.2.0
    - streamlit>=1.28.0