"""
Alert system for sending notifications
"""
import smtplib
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, Any, Dict
from utils.logger import setup_logger
import logging

class AlertSystem:
    """Alert system for sending notifications"""

    def __init__(self, config: Any) -> None:
        self.config = config
        self.logger: logging.Logger = logging.getLogger("TradingBot")

    def send_alert(self, message: str, level: str = "info") -> None:
        """
        Send alert according to configuration

        Args:
            message: Message to send
            level: Alert level (info, warning, error)
        """
        try:
            if self.config.enable_email_alerts:
                self._send_email(message, level)

            if self.config.enable_slack_alerts:
                self._send_slack(message, level)

            self.logger.info(f"Alert sent: {level} - {message[:50]}...")

        except Exception as e:
            self.logger.error(f"Error sending alert: {e}")

    def _send_email(self, message: str, level: str) -> None:
        """Send email alert"""
        if not all([self.config.smtp_server, self.config.alert_email]):
            return

        try:
            # Create email
            msg = MIMEMultipart()
            msg['From'] = self.config.alert_email
            msg['To'] = self.config.alert_email
            msg['Subject'] = f"Trading Bot Alert - {level.upper()}"

            body = f"""
            Trading Bot Alert
            =================

            Level: {level.upper()}
            Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

            Message:
            {message}

            ---
            Automatically generated by trading bot
            """

            msg.attach(MIMEText(body, 'plain'))

            # Send email
            server = smtplib.SMTP(self.config.smtp_server, self.config.smtp_port)
            server.starttls()
            server.login(self.config.alert_email, self.config.alert_email_password)
            text = msg.as_string()
            server.sendmail(self.config.alert_email, self.config.alert_email, text)
            server.quit()

        except Exception as e:
            self.logger.error(f"Error sending email: {e}")

    def _send_slack(self, message: str, level: str) -> None:
        """Send Slack notification"""
        if not self.config.slack_webhook_url:
            return

        try:
            # Emoji by level
            emoji_map = {
                "info": ":information_source:",
                "warning": ":warning:",
                "error": ":rotating_light:"
            }

            emoji = emoji_map.get(level, ":robot_face:")

            payload = {
                "text": f"{emoji} Trading Bot Alert",
                "attachments": [
                    {
                        "color": "danger" if level == "error" else "warning" if level == "warning" else "good",
                        "fields": [
                            {
                                "title": "Level",
                                "value": level.upper(),
                                "short": True
                            },
                            {
                                "title": "Time",
                                "value": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                                "short": True
                            },
                            {
                                "title": "Message",
                                "value": message,
                                "short": False
                            }
                        ]
                    }
                ]
            }

            response = requests.post(self.config.slack_webhook_url, json=payload)
            response.raise_for_status()

        except Exception as e:
            self.logger.error(f"Error sending Slack notification: {e}")