global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trading-bot-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-bot-host'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-postgres'

  - job_name: 'trading-bot'
    static_configs:
      - targets: ['app:8000']  # Trading bot metrics
    metrics_path: '/metrics'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-bot-app'